title: Sichun Li # your name (or website title) here
logo: "/images/config2.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  A data-driven storyteller,  <br>  
  a fast learner,  <br>  
  a critical thinker  <br>
  <br>
  <a href="https://www.linkedin.com/in/sichun-li-aa9a92192/">View My LinkedIn Profile</a> 
  


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
