title: Sichun Li # your name (or website title) here
logo: "files/config2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my little analytics wonderland!
  <br><br>
  A data-driven storyteller,  <br>  
  a fast learner,  <br>  
  a critical thinker  <br>
  <br><br>
  <a href="https://www.linkedin.com/in/sichun-li-aa9a92192/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
